<?php
    /* get config from themesetting */
    $setting = Mage::helper('rainbowsettings');
    $fonts = Mage::getModel('rainbowsettings/config_font')->toOptionArray();
    $boxwide = Mage::getModel('rainbowsettings/config_boxwide')->toOptionArray();
    $tmf = $setting->getMenu_TmFont();
    $h5f = $setting->getTypography_H5Font();
    if($tmf==""){
        $tmf=$h5f;
    }
    $ischecked = $setting->getGeneral_WideslideFull();
	$check = $setting->getGeneral_DisableFrontendVariation();
?>
<?php if($check != 1) : ?><a href="javascript:void(0)" class="btn-toggle hide-lte0">+ open/close</a><?php endif;?>
<div id="demotool_variation" class="hide-lte0">
	<div class="variation-cp" style="display:none">
		<div class="demotool-title">Magento Theme Variations</div>
		<form method="get" name="emvariationform" id="emvariationform" action="<?php echo $this->getSkinUrl('css/theme.css.php') ?>">
		<div class="demotool-content">
            <!-- Google Fonts -->
			<div class="demo demo-02">
				<div class="content-title"><span>Google Fonts</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Import these google fonts</div>
									<div class="input">
										<select id="em_variation_google_font" multiple="true" rows="10" size="10">
											<?php $selectedFonts = explode(',', $setting->getTypography_GoogleFonts()) ?>
											<?php foreach ($fonts as $_font): ?>
											<option value="<?php echo htmlspecialchars($_font['value']) ?>" <?php echo @in_array($_font['value'], $selectedFonts) ? 'selected="selected"' : '' ?>><?php echo $_font['label'] ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="desc">Select which google fonts should be imported to your site</div>
								</div>
							</div>
						</div>
					</div>
				</div>					
			</div>
			
			<!-- Element Fonts -->
			<div class="demo demo-03">
				<div class="content-title"><span>Element Fonts</span></div>
				<div class="wrapper-content">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">General Font</div>
									<div class="input"><input type="text" name="general_font" value="<?php echo htmlspecialchars($setting->getTypography_GeneralFont()) ?>" class="input-text"/></div>
									<div class="desc">Font for body, content, text...<br/>E.g. <em>12px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H1</div>
									<div class="input"><input type="text" name="h1_font" value="<?php echo htmlspecialchars($setting->getTypography_H1Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 22px/1.15 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H2</div>
									<div class="input"><input type="text" name="h2_font" value="<?php echo htmlspecialchars($setting->getTypography_H2Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. normal <em>20px/1.25 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H3</div>
									<div class="input"><input type="text" name="h3_font" value="<?php echo htmlspecialchars($setting->getTypography_H3Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 18px/1.25 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H4</div>
									<div class="input"><input type="text" name="h4_font" value="<?php echo htmlspecialchars($setting->getTypography_H4Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 16px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
								<div class="row">
									<div class="label">H5</div>
									<div class="input"><input type="text" name="h5_font" value="<?php echo htmlspecialchars($setting->getTypography_H5Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 14px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
                                <div class="row">
									<div class="label">H6</div>
									<div class="input"><input type="text" name="h6_font" value="<?php echo htmlspecialchars($setting->getTypography_H6Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 12px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- General -->
			<div class="demo demo-02">
				<div class="content-title"><span>Choose Your Layout Style</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
							<div class="col">
								<div class="row">
									<div class="label">Box/Wide Mode</div>
									<div class="input">
                                        <select id="em_box_wide" name="em_box_wide" class="em_box_wide select">
                                            <?php $selectedBoxWide = explode(',', $setting->getGeneral_BoxWide()) ?>
                                            <?php foreach ($boxwide as $boxwide_item): ?>
											     <option value="<?php echo htmlspecialchars($boxwide_item['value']) ?>" <?php echo @in_array($boxwide_item['value'], $selectedBoxWide) ? 'selected="selected"' : '' ?>><?php echo $boxwide_item['label'] ?></option>
											<?php endforeach ?>
                                        </select>
									</div>
									<div class="desc">Default: Wide</div>
								</div>
                                <div class="row" id="emoption_wideslideshow">
                                    <div class="input">
                                        <input id="wide_full" class="full_slideshow" type="checkbox" name="wide_full" value="wide_full" <?php if($ischecked!=0):?>checked<?php endif;?> /><span>Full Slideshow</span>
                                    </div>
                                </div>
                                <div class="row box_item">
									<div class="label">Page Background Color</div>
									<div class="input"><input type="text" name="p_bg_color" value="<?php echo htmlspecialchars($setting->getGeneral_PBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default #ffffff</div>
								</div>
                                <div class="row box_item">
									<div class="label">Page Background Pattern</div>
									<div class="input">
										<input type="hidden" name="page_bg_image" value="url(../images/stripes/<?php echo htmlspecialchars($setting->getGeneral_PageBgImage()) ?>)"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galarainbow/images/stripes/'; ?>
										<?php foreach (Mage::getModel('rainbowsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="page_bg_image<?php echo $setting->getGeneral_PageBgImage() == $row['value'] ? ' selected' : '' ?>" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" >
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
                                <div class="row box_item">
									<div class="label">Page Background Position</div>
									<div class="input"><input type="text" name="page_bg_position" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
								</div>
                                <div class="row box_item">
									<div class="label">Page Background Repeat</div>
									<div class="input"><input type="text" name="page_bg_repeat" value="<?php echo htmlspecialchars($setting->getGeneral_PageBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Header -->
			<div class="demo demo-01">
				<div class="content-title"><span>Header</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
								<div class="row" style="min-height:135px">
									<div class="label">Header Text Color</div>
									<div class="input"><input type="text" name="h_text_color" value="<?php echo htmlspecialchars($setting->getHeader_HTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in text header<br/>Default: #aaaaaa</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Text 4 Color</div>
									<div class="input"><input type="text" name="h_text4_color" value="<?php echo htmlspecialchars($setting->getHeader_HText4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color in title dropdown cart<br/>Default: #000000</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Background 2 Color</div>
									<div class="input"><input type="text" name="h_bg2_color" value="<?php echo htmlspecialchars($setting->getHeader_HBg2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in top header.<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Line Color</div>
									<div class="input"><input type="text" name="h_line_color" value="<?php echo htmlspecialchars($setting->getHeader_HLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line header<br/>Default: #c2c1c1</div>
								</div>
							</div>

							<div class="col col-1">
								<div class="row" style="min-height:135px">
									<div class="label">Header Text 2 Color</div>
									<div class="input"><input type="text" name="h_text2_color" value="<?php echo htmlspecialchars($setting->getHeader_HText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in text hover/active<br/>Default: #fb687b</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Text 5 Color</div>
									<div class="input"><input type="text" name="h_text5_color" value="<?php echo htmlspecialchars($setting->getHeader_HText5Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color in text free account<br/>Default: #000000</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Background 3 Color</div>
									<div class="input"><input type="text" name="h_bg3_color" value="<?php echo htmlspecialchars($setting->getHeader_HBg3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in top header.<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Line 2 Color</div>
									<div class="input"><input type="text" name="h_line2_color" value="<?php echo htmlspecialchars($setting->getHeader_HLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line header<br/>Default: #ea988d</div>
								</div>
                            </div>

                            <div class="col col-1">
								<div class="row" style="min-height:135px">
									<div class="label">Header Text 3 Color</div>
									<div class="input"><input type="text" name="h_text3_color" value="<?php echo htmlspecialchars($setting->getHeader_HText3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color in title<br/>Default: #000000</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Background Color</div>
									<div class="input"><input type="text" name="h_bg_color" value="<?php echo htmlspecialchars($setting->getHeader_HBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in header.<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Background 4 Color</div>
									<div class="input"><input type="text" name="h_bg4_color" value="<?php echo htmlspecialchars($setting->getHeader_HBg4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in title cart.<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:135px">
									<div class="label">Header Line 3 Color</div>
									<div class="input"><input type="text" name="h_line3_color" value="<?php echo htmlspecialchars($setting->getHeader_HLine3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line header<br/>Default: #ea988d</div>
								</div>
                            </div>

							<div class="col">
								<div class="row">
									<div class="label">Header Background Pattern</div>
									<div class="input">
										<input type="hidden" name="h_bg_image" value="url(../images/stripes/<?php echo htmlspecialchars($setting->getHeader_HBgImage()) ?>)"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galarainbow/images/stripes/'; ?>
										<?php foreach (Mage::getModel('rainbowsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="h_bg_image<?php echo $setting->getHeader_HBgImage() == $row['value'] ? ' selected' : '' ?>" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" >
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Header Background Position</div>
									<div class="input"><input type="text" name="h_bg_position" value="<?php echo htmlspecialchars($setting->getHeader_HBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Header Background Repeat</div>
									<div class="input"><input type="text" name="h_bg_repeat" value="<?php echo htmlspecialchars($setting->getHeader_HBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
								</div>
							</div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Top Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Top Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
								<div class="row">
									<div class="label">Top Menu Background Color</div>
									<div class="input"><input type="text" name="tm_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_TmBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in top menu, normal text...<br/>Default: #fb687b</div>
								</div>
								
								<div class="row">
									<div class="label">Top Menu Hover/Active Text Color</div>
									<div class="input"><input type="text" name="tm_hover_text_color" value="<?php echo htmlspecialchars($setting->getMenu_TmHoverTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color hover text used in top menu, normal text...<br/>Default: #ffffff </div>
								</div>
                            </div>

                            <div class="col col-1">
								<div class="row">
									<div class="label">Top Menu Hover Background Color</div>
									<div class="input"><input type="text" name="tm_hover_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_TmHoverBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color when hover top menu, normal text...<br/>Default: #000000</div>
								</div>
								
								<div class="row">
									<div class="label">Menu Line Color</div>
									<div class="input"><input type="text" name="tm_line_color" value="<?php echo htmlspecialchars($setting->getMenu_TmLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color<br/>Default: #f14c61</div>
								</div>
								
                            </div>
							 <div class="col col-1">
								<div class="row">
									<div class="label">Top Menu Text Color</div>
									<div class="input"><input type="text" name="tm_text_color" value="<?php echo htmlspecialchars($setting->getMenu_TmTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color text used in top menu, normal text...<br/>Default: #ffffff</div>
								</div>
								<div class="row">
									<div class="label">Menu Line 2 Color</div>
									<div class="input"><input type="text" name="tm_line2_color" value="<?php echo htmlspecialchars($setting->getMenu_TmLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default line top menu color<br/>Default: #ffffff</div>
								</div>
                            </div>

                            <div class="col">
                                <div class="row">
									<div class="label">Top Menu Font</div>
									<div class="input"><input type="text" name="tm_font" value="<?php echo htmlspecialchars($setting->getMenu_TmFont()) ?>" class="input-text"/></div>
									<div class="desc">Font for body, content, text...<br/>E.g. <em>16px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Dropdown Menu -->
			<div class="demo demo-01">
				<div class="content-title"><span>Dropdown Menu</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Background Color</div>
									<div class="input"><input type="text" name="dm_bg_color" value="<?php echo htmlspecialchars($setting->getMenu_DmBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in dropdown menu, normal text... <br/>Default: #ffffff </div>
								</div>
								<div class="row">
									<div class="label">Dropdown Menu Text 3 Color</div>
									<div class="input"><input type="text" name="dm_text3_color" value="<?php echo htmlspecialchars($setting->getMenu_DmText3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in title link.<br/>Default: #191919</div>
								</div>
                            </div>

                            <div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Text Color</div>
									<div class="input"><input type="text" name="dm_text_color" value="<?php echo htmlspecialchars($setting->getMenu_DmTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in dropdown menu, normal text...<br/>Default: #555555</div>
								</div>
								
                            </div>

							<div class="col col-1">
                                <div class="row">
									<div class="label">Dropdown Menu Text 2 Color</div>
									<div class="input"><input type="text" name="dm_text2_color" value="<?php echo htmlspecialchars($setting->getMenu_DmText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in hover/active text.<br/>Default: #fb687b</div>
								</div>
                            </div>

                            <div class="col">
                                <div class="row">
									<div class="label">Dropdown Menu Font</div>
									<div class="input"><input type="text" name="dm_font" value="<?php echo htmlspecialchars($setting->getMenu_DmFont()) ?>" class="input-text"/></div>
									<div class="desc">Font for body, content, text...<br/>E.g. <em>12px/1.35 Arial,Helvetica,sans-serif</em></div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Body -->
			<div class="demo demo-01">
				<div class="content-title"><span>Body</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
								<div class="row" style="min-height:120px">
									<div class="label">Body Background Color</div>
									<div class="input"><input type="text" name="bd_bg_color" value="<?php echo htmlspecialchars($setting->getBody_BdBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in body.<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Background 4 Color</div>
									<div class="input"><input type="text" name="bd_bg4_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in tab slider home page<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 2 Color</div>
									<div class="input"><input type="text" name="bd_text2_color" value="<?php echo htmlspecialchars($setting->getBody_BdText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in normal text.<br/>Default: #505050</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 5 Color</div>
									<div class="input"><input type="text" name="bd_text5_color" value="<?php echo htmlspecialchars($setting->getBody_BdText5Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in label, title tab active ... <br/>Default:#ffffff</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 8 Color</div>
									<div class="input"><input type="text" name="bd_text8_color" value="<?php echo htmlspecialchars($setting->getBody_BdText8Color()) ?>" class="color-picker" /></div>
									<div class="desc">The color used in text title tab<br/>Default: #191919 <br/>Default: #6ad98a</div>
								</div>
								<div class="row">
									<div class="label">Body Line 3 Color</div>
									<div class="input"><input type="text" name="bd_line3_color" value="<?php echo htmlspecialchars($setting->getBody_BdLine3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color used in border title tab.<br/>Default: #000000</div>
								</div>
							</div>

							<div class="col col-1">
								<div class="row" style="min-height:120px">
									<div class="label">Body Background 2 Color</div>
									<div class="input"><input type="text" name="bd_bg2_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in title tab...<br/>Default: #000000</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Background 5 Color</div>
									<div class="input"><input type="text" name="bd_bg5_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg5Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in title block<br/>Default: #ffffff</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 3 Color</div>
									<div class="input"><input type="text" name="bd_text3_color" value="<?php echo htmlspecialchars($setting->getBody_BdText3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in normal text.<br/>Default: #a0a0a0</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 6 Color</div>
									<div class="input"><input type="text" name="bd_text6_color" value="<?php echo htmlspecialchars($setting->getBody_BdText6Color()) ?>" class="color-picker" /></div>
									<div class="desc">The color used in text in stock...<br/>Default: #6ad98a</div>
								</div>
								<div class="row">
									<div class="label">Body Line 1 Color</div>
									<div class="input"><input type="text" name="bd_line_color" value="<?php echo htmlspecialchars($setting->getBody_BdLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">The line used in border input, select, box, table...<br/>Default: #e6e6e6</div>
								</div>
								<div class="row">
									<div class="label">Body Line 4 Color</div>
									<div class="input"><input type="text" name="bd_line4_color" value="<?php echo htmlspecialchars($setting->getBody_BdLine4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color used in border title block.<br/>Default: #000000</div>
								</div>
							</div>

							<div class="col col-1">
								<div class="row" style="min-height:120px">
									<div class="label">Body Background 3 Color</div>
									<div class="input"><input type="text" name="bd_bg3_color" value="<?php echo htmlspecialchars($setting->getBody_BdBg3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in block, toolbar category ...<br/>Default: #fafafa</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text Color</div>
									<div class="input"><input type="text" name="bd_text_color" value="<?php echo htmlspecialchars($setting->getBody_BdTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in product name, title tab, title block...<br/>Default: #191919</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 4 Color</div>
									<div class="input"><input type="text" name="bd_text4_color" value="<?php echo htmlspecialchars($setting->getBody_BdText4Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in text hover/active ... <br/>Default: #fb687b</div>
								</div>
								<div class="row" style="min-height:120px">
									<div class="label">Body Text 7 Color</div>
									<div class="input"><input type="text" name="bd_text7_color" value="<?php echo htmlspecialchars($setting->getBody_BdText7Color()) ?>" class="color-picker" /></div>
									<div class="desc">The color used in text title block<br/>Default: #6ad98a</div>
								</div>
								<div class="row">
									<div class="label">Body Line 2 Color</div>
									<div class="input"><input type="text" name="bd_line2_color" value="<?php echo htmlspecialchars($setting->getBody_BdLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default line color used in border title checkout, account dashboard, title block.<br/>Default: #000000</div>
								</div>
                            </div>

							<div class="col">
								<div class="row">
									<div class="label">Body Background Pattern</div>
									<div class="input">
										<input type="hidden" name="bd_bg_image" value="url(../images/stripes/<?php echo htmlspecialchars($setting->getBody_BdBgImage()) ?>)"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galarainbow/images/stripes/'; ?>
										<?php foreach (Mage::getModel('rainbowsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="bd_bg_image<?php echo $setting->getBody_BdBgImage() == $row['value'] ? ' selected' : '' ?>" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" >
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Body Background Position</div>
									<div class="input"><input type="text" name="bd_bg_position" value="<?php echo htmlspecialchars($setting->getBody_BdBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Body Background Repeat</div>
									<div class="input"><input type="text" name="bd_bg_repeat" value="<?php echo htmlspecialchars($setting->getBody_BdBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
								</div>
							</div>

                            <div class="col">
								<div class="row">
									<div class="label">Box Shadow</div>
									<div class="input"><input type="text" name="bd_box_shadow" value="<?php echo htmlspecialchars($setting->getBody_BdBoxShadow()) ?>" class="input-text"/></div>
									<div class="desc">Configure box shadow for box, widgets, slider. No box shadow by default.<br/>E.g. <span style="box-shadow:0 0 5px #e0e0e0">0 0 5px #e0e0e0</span></div>
								</div>
								<div class="row">
									<div class="label">Rounded Corner</div>
									<div class="input"><input type="text" name="bd_rounded_corner" value="<?php echo htmlspecialchars($setting->getBody_BdRoundedCorner()) ?>" class="input-text"/></div>
									<div class="desc">Default rounded corner used in button, input, dropdown menu...<br/>E.g. <span style="border:1px solid #333333; padding:5px; display:inline-block; border-radius:5px">0px</span></div>
								</div>
                                <input type="hidden" name="additional_css_file" value="<?php echo htmlspecialchars($setting->getTypography_AdditionalCssFile()) ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Footer -->
			<div class="demo demo-01">
				<div class="content-title"><span>Footer</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
								<div class="row">
									<div class="label">Footer Background Color</div>
									<div class="input"><input type="text" name="f_bg_color" value="<?php echo htmlspecialchars($setting->getFooter_FBgColor()) ?>" class="color-picker" /></div>
									<div class="desc">The color used in background<br/>Default: #ffffff</div>
								</div>
								<div class="row">
									<div class="label">Footer Text 2 Color</div>
									<div class="input"><input type="text" name="f_text2_color" value="<?php echo htmlspecialchars($setting->getFooter_FText2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in footer title.<br/>Default: #191919</div>
								</div>
								<div class="row">
									<div class="label">Footer Line 2 Color</div>
									<div class="input"><input type="text" name="f_line2_color" value="<?php echo htmlspecialchars($setting->getFooter_FLine2Color()) ?>" class="color-picker" /></div>
									<div class="desc">The line used in border top footer<br/>Default: #d2d2d2</div>
								</div>
                            </div>

                            <div class="col col-1">
								<div class="row">
									<div class="label">Footer Background 2 Color</div>
									<div class="input"><input type="text" name="f_bg2_color" value="<?php echo htmlspecialchars($setting->getFooter_FBg2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in footer popular.<br/>Default: #eeeeee</div>
								</div>
								<div class="row">
									<div class="label">Footer Text 3 Color</div>
									<div class="input"><input type="text" name="f_text3_color" value="<?php echo htmlspecialchars($setting->getFooter_FText3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in footer address.<br/>Default: #a0a0a0</div>
								</div>
								
                            </div>

                            <div class="col col-1">
								<div class="row">
									<div class="label">Footer Text 1 Color</div>
									<div class="input"><input type="text" name="f_text_color" value="<?php echo htmlspecialchars($setting->getFooter_FTextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default text color used in footer<br/>Default: #555555</div>
								</div>
								<div class="row">
									<div class="label">Footer Line Color</div>
									<div class="input"><input type="text" name="f_line_color" value="<?php echo htmlspecialchars($setting->getFooter_FLineColor()) ?>" class="color-picker" /></div>
									<div class="desc">The line used in border top footer<br/>Default: #d2d2d2</div>
								</div>
                            </div>

							<div class="col">
								<div class="row">
									<div class="label">Footer Background Pattern</div>
									<div class="input">
										<input type="hidden" name="f_bg_image" value="url(../images/stripes/<?php echo htmlspecialchars($setting->getFooter_FBgImage()) ?>)"  />
										<?php $imgDir = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/default/galarainbow/images/stripes/'; ?>
										<?php foreach (Mage::getModel('rainbowsettings/config_stripes')->toOptionArray() as $row):?>
										<a href="#" class="f_bg_image<?php echo $setting->getFooter_FBgImage() == $row['value'] ? ' selected' : '' ?>" data-input-value="<?php echo htmlspecialchars($row['value']) ?>" >
											<img src="<?php echo $imgDir . 'blank.gif' ?>" style="background-image:url(<?php echo $imgDir . $row['value'] ?>)" alt="" />
										</a>
										<?php endforeach ?>
									</div>
									<div class="desc">Specify background pattern image.</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Footer Background Position</div>
									<div class="input"><input type="text" name="f_bg_position" value="<?php echo htmlspecialchars($setting->getFooter_FBgPosition()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: left top, left center, left bottom,right top, right center, right bottom,center top,center center,center bottom,x% y%, xpos ypos, inherit<br/>Default: 0 0</div>
								</div>
							</div>

							<div class="col">
								<div class="row">
									<div class="label">Footer Background Repeat</div>
									<div class="input"><input type="text" name="f_bg_repeat" value="<?php echo htmlspecialchars($setting->getFooter_FBgRepeat()) ?>" class="input-text"/></div>
									<div class="desc">Property Values: repeat, repeat-x, repeat-y, no-repeat, inherit<br /> Default: repeat</div>
								</div>
							</div>

                        </div>
                    </div>
                </div>
            </div>

			<!-- 1st Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>1st Button Default</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Background Color</div>
									<div class="input"><input type="text" name="btn1_bg_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1BgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in button</div>
								</div>
								 <div class="row">
									<div class="label">Button Line 2 Color</div>
									<div class="input"><input type="text" name="btn1_line2_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1Line2Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line</div>
								</div>
                            </div>

                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Text Color</div>
									<div class="input"><input type="text" name="btn1_text_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1TextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in button text</div>
								</div>
								 <div class="row">
									<div class="label">Button Line 3 Color</div>
									<div class="input"><input type="text" name="btn1_line3_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1Line3Color()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line</div>
								</div>
                            </div>

                            <div class="col col-1">
                                <div class="row">
									<div class="label">1st Button Line Color</div>
									<div class="input"><input type="text" name="btn1_line_color" value="<?php echo htmlspecialchars($setting->getButton_Btn1LineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line</div>
								</div>
                            </div>

                            <div class="col">
								<div class="row">
									<div class="label">1st Button Font</div>
									<div class="input"><input type="text" name="btn1_font" value="<?php echo htmlspecialchars($setting->getButton_Btn1Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 11px/1.35 helvetica,arial,sans-serif</em></div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 2nd Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>2nd Button (button checkout dropdown cart...)</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Background Color</div>
									<div class="input"><input type="text" name="btn2_bg_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2BgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in button</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Text Color</div>
									<div class="input"><input type="text" name="btn2_text_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2TextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in button text</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">2nd Button Line Color</div>
									<div class="input"><input type="text" name="btn2_line_color" value="<?php echo htmlspecialchars($setting->getButton_Btn2LineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line</div>
								</div>
                            </div>
                            
                            <div class="col">
								<div class="row">
									<div class="label">2nd Button Font</div>
									<div class="input"><input type="text" name="btn2_font" value="<?php echo htmlspecialchars($setting->getButton_Btn2Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 22px/1.15 helvetica,arial,sans-serif</em></div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
			
		<!-- 3rd Buttons -->
			<div class="demo demo-01">
				<div class="content-title"><span>3rd Button (button checkout ...)</span></div>
				<div class="wrapper-content general-setting">
					<div class="box last">
						<div class="content">
                            <div class="col col-1">
                                <div class="row">
									<div class="label">3rd Button Background Color</div>
									<div class="input"><input type="text" name="btn3_bg_color" value="<?php echo htmlspecialchars($setting->getButton_Btn3BgColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default background color used in button</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">3rd Button Text Color</div>
									<div class="input"><input type="text" name="btn3_text_color" value="<?php echo htmlspecialchars($setting->getButton_Btn3TextColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in button text</div>
								</div>
                            </div>
                            
                            <div class="col col-1">
                                <div class="row">
									<div class="label">3rd Button Line Color</div>
									<div class="input"><input type="text" name="btn3_line_color" value="<?php echo htmlspecialchars($setting->getButton_Btn3LineColor()) ?>" class="color-picker" /></div>
									<div class="desc">Default color used in line</div>
								</div>
                            </div>
                            
                            <div class="col">
								<div class="row">
									<div class="label">3rd Button Font</div>
									<div class="input"><input type="text" name="btn3_font" value="<?php echo htmlspecialchars($setting->getButton_Btn3Font()) ?>" class="input-text" /></div>
									<div class="desc">E.g. <em>normal 22px/1.15 helvetica,arial,sans-serif</em></div>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		<!-- end 3rd button-->
            
			<a href="#" class="btn-reset">Reset</a>
			<a href="#" class="btn-apply">Apply Changes</a>
		</div>
		<div class="copyright">Theme designed by <a href="http://galathemes.com" title="Premium Magento Themes &amp; Premium Magento Templates" target="_blank">GalaThemes.com</a></div>
		</form>
	</div>
</div>