<div class="header_top">
	<div class="grid_9 alpha">
		<?php echo $this->getChildHtml('galarainbow_header_support') ?>
	</div>
	<div class="grid_15 omega">
		
		<?php echo $this->getChildHtml('store_switcher_header') ?>
		<?php echo $this->getChildHtml('currency') ?>
		<?php echo $this->getChildHtml('store_language') ?>
		<?php echo $this->getChildHtml('topLinks') ?>
		
	</div>
	<div class="clear"></div>
</div>